"""Request and response schemas for the Task resource."""

from pydantic import BaseModel, ConfigDict, Field


class TaskBase(BaseModel):
    """Define fields shared by every Task schema."""

    # These type hints and Field constraints validate data at runtime and also
    # become part of the OpenAPI contract displayed by Swagger UI.
    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    title: str = Field(
        min_length=1,
        max_length=120,
        description="A short description of the work to complete.",
        examples=["Document the API"],
    )
    description: str = Field(
        min_length=1,
        max_length=500,
        description="Additional details about the task.",
        examples=["Add useful summaries, descriptions, and examples."],
    )
    completed: bool = Field(
        default=False,
        description="Whether the task has been completed.",
        examples=[False],
    )
    project_id: int = Field(
        gt=0,
        description="The identifier of the project that owns this task.",
        examples=[1],
    )


class TaskCreate(TaskBase):
    """Validate the body used to create a Task."""


class TaskUpdate(TaskBase):
    """Validate the replacement body used to update a Task."""


class TaskResponse(TaskBase):
    """Describe a Task returned by the API."""

    # Allow FastAPI to serialize a SQLAlchemy Task object through this schema.
    model_config = ConfigDict(from_attributes=True)

    id: int = Field(
        gt=0,
        description="The unique identifier generated by the server.",
        examples=[1],
    )
